services:
  finsight-api:
    build: .
    ports:
      - "8000:8000"

    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped